apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: discord-bot
spec:
  replicas: 1

  selector:
    matchLabels:
      app: discord-bot

  template:
    metadata:
      labels:
        app: discord-bot

    spec:
      containers:
        - name: discord-bot
          image: 740901968217.dkr.ecr.us-east-1.amazonaws.com/egm-prod-discord-bot:latest
          imagePullPolicy: Always

          ports:
            - name: bridge
              containerPort: 3001
              protocol: TCP

          envFrom:
            - secretRef:
                name: discord-bot-config

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"